/*
 * Auto-generated header for Livestock Health Monitor
 * Deploy on ARM Cortex-M4 or similar MCU
 * Generated by edge_optimize.py
 */

#ifndef LIVESTOCK_MODEL_H
#define LIVESTOCK_MODEL_H

#define NUM_FEATURES 10
#define NUM_CLASSES 4

/* Feature names */
#define FEATURE_0 "acc_variance"
#define FEATURE_1 "temp_deviation"
#define FEATURE_2 "heart_rate"
#define FEATURE_3 "rumination_rate"
#define FEATURE_4 "hr_rolling_std"
#define FEATURE_5 "hr_rolling_range"
#define FEATURE_6 "activity_rolling_std"
#define FEATURE_7 "activity_rolling_range"
#define FEATURE_8 "movement_consistency"
#define FEATURE_9 "hr_temp_ratio"

/* Scaler means */
static const float SCALER_MEAN[10] = {
    0.060785f, 0.873269f, 76.164486f, 31.167083f, 9.715131f, 39.931803f, 0.324288f, 1.340924f, 300.012098f, 1.954571f
};

/* Scaler scales (std dev) */
static const float SCALER_SCALE[10] = {
    0.093663f, 0.649267f, 23.649769f, 18.553116f, 5.436930f, 22.667203f, 0.256783f, 1.050804f, 381.960837f, 0.586076f
};

/* Class labels */
static const char* CLASS_0 = "Healthy";
static const char* CLASS_1 = "Sick";
static const char* CLASS_2 = "Stressed";
static const char* CLASS_3 = "Inactive";

/* Normalize a feature value */
static inline float normalize_feature(int idx, float value) {
    return (value - SCALER_MEAN[idx]) / SCALER_SCALE[idx];
}

/* ============================================ */
/* Logistic Regression Weights (full inference) */
/* ============================================ */

static const float LR_COEF[4][10] = {
    {0.241201f, -1.837935f, -0.472136f, 2.331521f, -0.080003f, -0.413739f, 0.070340f, -0.235253f, -0.391403f, -0.439309f},
    {-0.960192f, 1.427176f, 0.511602f, -0.908657f, 1.628589f, 1.340963f, -0.464148f, -0.154074f, 0.403700f, 0.564534f},
    {1.945787f, 0.108734f, 0.997274f, -0.064892f, -0.185891f, -0.144228f, 2.527507f, 1.822654f, -0.551855f, 0.872162f},
    {-1.226797f, 0.302026f, -1.036741f, -1.357972f, -1.362695f, -0.782995f, -2.133700f, -1.433327f, 0.539558f, -0.997386f},
};

static const float LR_INTERCEPT[4] = {
    0.689652f, 1.275414f, 0.149525f, -2.114591f
};

/* Softmax + argmax prediction */
static int predict_health_state(float features[NUM_FEATURES]) {
    float normalized[NUM_FEATURES];
    for (int i = 0; i < NUM_FEATURES; i++) {
        normalized[i] = normalize_feature(i, features[i]);
    }

    float max_score = -1e9f;
    int best_class = 0;
    for (int c = 0; c < NUM_CLASSES; c++) {
        float score = LR_INTERCEPT[c];
        for (int f = 0; f < NUM_FEATURES; f++) {
            score += LR_COEF[c][f] * normalized[f];
        }
        if (score > max_score) {
            max_score = score;
            best_class = c;
        }
    }
    return best_class;
}

#endif /* LIVESTOCK_MODEL_H */